// 자동 생성 — 직접 수정 금지. `npm run bindings`로 재생성하세요.
// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE, Channel } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	listStorageRoots: () => __TAURI_INVOKE<string[]>("list_storage_roots"),
	listMediaDirectory: (path: string) => typedError<MediaDirectoryEntry[], EngineError>(__TAURI_INVOKE("list_media_directory", { path })),
	searchMediaDirectory: (path: string, query: string) => typedError<MediaDirectoryEntry[], EngineError>(__TAURI_INVOKE("search_media_directory", { path, query })),
	engineInit: () => typedError<null, EngineError>(__TAURI_INVOKE("engine_init")),
	engineDispose: () => typedError<null, EngineError>(__TAURI_INVOKE("engine_dispose")),
	engineLoadAudioFile: (path: string, onProgress: Channel<DecodeProgress>) => typedError<NativeAssetInfo, EngineError>(__TAURI_INVOKE("engine_load_audio_file", { path, onProgress })),
	engineUnloadAsset: (assetId: string) => typedError<null, EngineError>(__TAURI_INVOKE("engine_unload_asset", { assetId })),
	engineAssetPeaks: (assetId: string, lod: number) => typedError<(number | null)[], EngineError>(__TAURI_INVOKE("engine_asset_peaks", { assetId, lod })),
	engineSyncGraph: (snapshot: GraphSnapshot) => typedError<null, EngineError>(__TAURI_INVOKE("engine_sync_graph", { snapshot })),
	enginePlay: (fromSec: number | null, countInBars: number) => typedError<null, EngineError>(__TAURI_INVOKE("engine_play", { fromSec, countInBars })),
	engineSetMetronome: (enabled: boolean, gainDb: number | null, bpm: number | null, numerator: number, denominator: number) => typedError<null, EngineError>(__TAURI_INVOKE("engine_set_metronome", { enabled, gainDb, bpm, numerator, denominator })),
	enginePause: () => typedError<null, EngineError>(__TAURI_INVOKE("engine_pause")),
	engineStop: () => typedError<null, EngineError>(__TAURI_INVOKE("engine_stop")),
	engineSeek: (sec: number | null) => typedError<null, EngineError>(__TAURI_INVOKE("engine_seek", { sec })),
	engineSetTrackVolume: (trackId: string, gainDb: number | null) => typedError<null, EngineError>(__TAURI_INVOKE("engine_set_track_volume", { trackId, gainDb })),
	engineSetTrackPan: (trackId: string, pan: number | null) => typedError<null, EngineError>(__TAURI_INVOKE("engine_set_track_pan", { trackId, pan })),
	engineSetTrackMute: (trackId: string, muted: boolean) => typedError<null, EngineError>(__TAURI_INVOKE("engine_set_track_mute", { trackId, muted })),
	engineSetTrackSolo: (trackId: string, solo: boolean) => typedError<null, EngineError>(__TAURI_INVOKE("engine_set_track_solo", { trackId, solo })),
	engineSetSendLevel: (sendId: string, gainDb: number | null) => typedError<null, EngineError>(__TAURI_INVOKE("engine_set_send_level", { sendId, gainDb })),
	engineSetBusVolume: (busId: string, gainDb: number | null) => typedError<null, EngineError>(__TAURI_INVOKE("engine_set_bus_volume", { busId, gainDb })),
	engineSetMasterVolume: (gainDb: number | null) => typedError<null, EngineError>(__TAURI_INVOKE("engine_set_master_volume", { gainDb })),
	engineSetEffectParam: (effectId: string, paramId: string, value: number | null) => typedError<null, EngineError>(__TAURI_INVOKE("engine_set_effect_param", { effectId, paramId, value })),
	engineSetEffectBypass: (effectId: string, bypassed: boolean) => typedError<null, EngineError>(__TAURI_INVOKE("engine_set_effect_bypass", { effectId, bypassed })),
	engineSetInstrumentParam: (trackId: string, paramId: string, value: number | null) => typedError<null, EngineError>(__TAURI_INVOKE("engine_set_instrument_param", { trackId, paramId, value })),
	engineMidiNote: (trackId: string, noteId: number, pitch: number, velocity: number | null, noteOn: boolean) => typedError<null, EngineError>(__TAURI_INVOKE("engine_midi_note", { trackId, noteId, pitch, velocity, noteOn })),
	engineMidiAllNotesOff: (trackId: string) => typedError<null, EngineError>(__TAURI_INVOKE("engine_midi_all_notes_off", { trackId })),
	engineListMidiInputs: () => typedError<MidiInputPortInfo[], EngineError>(__TAURI_INVOKE("engine_list_midi_inputs")),
	engineConnectMidiInput: (portId: string, trackId: string) => typedError<null, EngineError>(__TAURI_INVOKE("engine_connect_midi_input", { portId, trackId })),
	engineDisconnectMidiInput: (portId: string) => typedError<null, EngineError>(__TAURI_INVOKE("engine_disconnect_midi_input", { portId })),
	enginePollState: () => typedError<EngineSnapshot, EngineError>(__TAURI_INVOKE("engine_poll_state")),
	engineListAudioBackends: () => typedError<AudioBackendInfo[], EngineError>(__TAURI_INVOKE("engine_list_audio_backends")),
	engineListOutputDevices: (backendId: string) => typedError<AudioDeviceInfo[], EngineError>(__TAURI_INVOKE("engine_list_output_devices", { backendId })),
	engineGetAudioSettings: () => typedError<AudioSettings, EngineError>(__TAURI_INVOKE("engine_get_audio_settings")),
	engineSetAudioSettings: (settings: AudioSettings) => typedError<null, EngineError>(__TAURI_INVOKE("engine_set_audio_settings", { settings })),
	engineExportProject: (request: ExportRequest, onProgress: Channel<ExportProgress>) => typedError<ExportResult, EngineError>(__TAURI_INVOKE("engine_export_project", { request, onProgress })),
	engineCancelExport: () => typedError<null, EngineError>(__TAURI_INVOKE("engine_cancel_export")),
	engineEqResponse: (effectId: string, points: number) => typedError<EqFrequencyResponse, EngineError>(__TAURI_INVOKE("engine_eq_response", { effectId, points })),
	engineOpenPluginEditor: (targetKind: string, targetId: string, foreground: boolean) => typedError<null, EngineError>(__TAURI_INVOKE("engine_open_plugin_editor", { targetKind, targetId, foreground })),
	engineClosePluginEditor: (targetKind: string, targetId: string) => typedError<null, EngineError>(__TAURI_INVOKE("engine_close_plugin_editor", { targetKind, targetId })),
	engineTakePluginEditorActions: (targetId: string) => typedError<string[], EngineError>(__TAURI_INVOKE("engine_take_plugin_editor_actions", { targetId })),
	engineSetPluginEditorHostState: (targetId: string, bypassed: boolean, automation: number) => typedError<null, EngineError>(__TAURI_INVOKE("engine_set_plugin_editor_host_state", { targetId, bypassed, automation })),
	enginePluginEditorIsOpen: (targetKind: string, targetId: string) => typedError<boolean, EngineError>(__TAURI_INVOKE("engine_plugin_editor_is_open", { targetKind, targetId })),
	engineSetPluginEditorPinned: (targetId: string, pinned: boolean) => typedError<null, EngineError>(__TAURI_INVOKE("engine_set_plugin_editor_pinned", { targetId, pinned })),
	engineSavePluginState: (targetKind: string, targetId: string) => typedError<number[], EngineError>(__TAURI_INVOKE("engine_save_plugin_state", { targetKind, targetId })),
	engineLoadPluginState: (targetKind: string, targetId: string, pluginState: number[]) => typedError<null, EngineError>(__TAURI_INVOKE("engine_load_plugin_state", { targetKind, targetId, pluginState })),
	cachedVst3Plugins: () => typedError<PluginDescriptor[], EngineError>(__TAURI_INVOKE("cached_vst3_plugins")),
	scanVst3Plugins: (paths: string[], force: boolean) => typedError<PluginDescriptor[], EngineError>(__TAURI_INVOKE("scan_vst3_plugins", { paths, force })),
	inspectPluginMetadata: (format: string, path: string, uid: string) => typedError<PluginDescriptor, EngineError>(__TAURI_INVOKE("inspect_plugin_metadata", { format, path, uid })),
	renderOfflineEffect: (req: OfflineRenderRequest) => typedError<OfflineRenderResult, EngineError>(__TAURI_INVOKE("render_offline_effect", { req })),
};

/* Types */
export type AudioBackendInfo = {
	id: string,
	name: string,
	available: boolean,
	asio: boolean,
};

export type AudioDeviceInfo = {
	id: string,
	name: string,
	isDefault: boolean,
	sampleRates: number[],
	bufferSizes: number[],
	channels: number,
};

export type AudioSettings = {
	backendId: string,
	deviceId: string,
	sampleRate: number,
	bufferSize: number,
};

export type BusSpec = {
	id: string,
	name: string,
	effects: EffectSpec[],
	volumeDb: number | null,
};

export type ClipGainPointSpec = {
	timeSec: number | null,
	valueDb: number | null,
	curve?: number | null,
};

export type ClipSpec = {
	id: string,
	assetId: string,
	startSec: number | null,
	offsetSec: number | null,
	durationSec: number | null,
	gainDb: number | null,
	fadeInSec: number | null,
	fadeOutSec: number | null,
	muted?: boolean,
	playbackRate?: number | null,
	pitchSemitones?: number | null,
	fineCents?: number | null,
	reversed?: boolean,
	fadeInCurve?: number | null,
	fadeOutCurve?: number | null,
	gainPoints?: ClipGainPointSpec[],
};

export type DecodeProgress = {
	stage: string,
	fraction: number | null,
};

export type EffectSpec = {
	id: string,
	type: string,
	bypassed: boolean,
	params: { [key in string]: number | null },
	plugin?: ExternalPluginRef | null,
	sidechain?: SidechainSpec | null,
};

export type EngineError = { kind: "DeviceNotFound"; detail: string } | { kind: "UnsupportedFormat"; detail: string } | { kind: "QueueFull" } | { kind: "Stream"; detail: string } | { kind: "Asset"; detail: string } | { kind: "InvalidRequest"; detail: string } | { kind: "Internal"; detail: string };

export type EngineSnapshot = {
	playheadSec: number | null,
	trackLevels: Level[],
	masterLevel: Level,
	stream: StreamStatus,
	graphRevision: number,
	playing: boolean,
	activeVoiceCounts: number[],
	multibandLevels: MultibandLevels[],
	distortionSpectra: ((number | null)[])[],
	limiterMetrics: LimiterMetrics[],
};

export type EqFrequencyResponse = {
	frequencies: (number | null)[],
	combinedDb: (number | null)[],
	bandsDb: ((number | null)[])[],
};

export type ExportProgress = {
	stage: string,
	renderedFrames: number,
	totalFrames: number,
	fraction: number | null,
};

export type ExportRequest = {
	outputPath: string,
	format: string,
	bitDepth: number,
	mp3BitrateKbps: number,
	sampleRate: number,
	normalize: boolean,
};

export type ExportResult = {
	outputPath: string,
	peakDb: number | null,
	clipped: boolean,
	cancelled: boolean,
};

export type ExternalPluginRef = {
	format: string,
	uid: string,
	name: string,
	vendor: string,
	path: string,
	audioInputBuses?: number,
	audioOutputBuses?: number,
	supportsSidechain?: boolean,
	hasEditor?: boolean,
	state?: number[],
};

export type GraphSnapshot = {
	tracks: TrackSpec[],
	buses: BusSpec[],
	master: MasterSpec,
	transport: TransportSpec,
};

export type InstrumentSpec = {
	id: string,
	type: string,
	params: { [key in string]: number | null },
	bypassed: boolean,
	plugin?: ExternalPluginRef | null,
};

export type Level = {
	peak: number | null,
	rms: number | null,
};

export type LimiterMetrics = {
	inputPeakDb: number | null,
	outputPeakDb: number | null,
	gainReductionDb: number | null,
	truePeakDb: number | null,
	momentaryLufs: number | null,
	shortTermLufs: number | null,
	integratedLufs: number | null,
};

export type LoopSpec = {
	enabled: boolean,
	startSec: number | null,
	endSec: number | null,
};

export type MasterSpec = {
	volumeDb: number | null,
	effects: EffectSpec[],
};

export type MediaDirectoryEntry = {
	path: string,
	name: string,
	isDirectory: boolean,
};

export type MidiCcLaneSpec = {
	/**  MIDI CC 0..127, or -1 for the bipolar pitch-bend wheel. */
	cc: number,
	points: MidiCcPointSpec[],
};

export type MidiCcPointSpec = {
	ticks: number,
	value: number,
};

export type MidiClipSpec = {
	id: string,
	name: string,
	startSec: number | null,
	durationSec: number | null,
	loopEnabled: boolean,
	loopStartTicks: number,
	loopLengthTicks: number,
	notes: MidiNoteSpec[],
	ccLanes?: MidiCcLaneSpec[],
	transposeSemitones: number,
	velocityScale: number | null,
	muted: boolean,
};

export type MidiInputPortInfo = {
	id: string,
	name: string,
	connected: boolean,
	targetTrackId: string | null,
};

export type MidiNoteSpec = {
	id: string,
	pitch: number,
	velocity: number,
	startTicks: number,
	lengthTicks: number,
	releaseVelocity: number,
	muted: boolean,
};

export type MultibandLevels = {
	low: StereoLevel,
	mid: StereoLevel,
	high: StereoLevel,
};

export type NativeAssetInfo = {
	id: string,
	path: string,
	name: string,
	durationSec: number | null,
	sampleRate: number,
	numChannels: number,
};

export type OfflineRenderRequest = {
	pluginUid: string,
	inputWavPath: string,
	outputWavPath: string,
	sampleRate: number,
	params: { [key in string]: number | null },
};

export type OfflineRenderResult = {
	outputWavPath: string,
	durationSec: number | null,
	peakDb: number | null,
};

export type PluginDescriptor = {
	format: string,
	uid: string,
	name: string,
	vendor: string,
	category: string,
	path: string,
	isInstrument: boolean,
	paramCount: number,
	hasEditor: boolean,
	audioInputBuses: number,
	audioOutputBuses: number,
	supportsSidechain: boolean,
	parameters: PluginParameterDescriptor[],
};

export type PluginParameterDescriptor = {
	id: string,
	name: string,
	module: string,
	min: number | null,
	max: number | null,
	defaultValue: number | null,
};

export type SendSpec = {
	id: string,
	targetBusId: string,
	gainDb: number | null,
	preFader: boolean,
};

export type SidechainSpec = {
	enabled: boolean,
	sourceTrackId: string | null,
};

export type StereoLevel = {
	left: number | null,
	right: number | null,
};

export type StreamStatus = {
	latencyMs: number | null,
	xruns: number,
	running: boolean,
	error: string | null,
	pdcSamples: number,
	/**  Smoothed audio-callback time divided by its realtime buffer budget. */
	cpuLoadPercent: number | null,
	/**  Short peak hold for spotting transient overloads that the average hides. */
	cpuPeakPercent: number | null,
	/**  Zero outside pre-count; otherwise the number of musical beats still to count. */
	countInBeatsRemaining: number,
};

export type TempoCurveSpec = "jump" | "linear";

export type TempoPointSpec = {
	tick: number,
	bpm: number | null,
	curve?: TempoCurveSpec,
};

export type TimeSignaturePointSpec = {
	/**  One-based bar number. Signature changes are therefore always bar-aligned. */
	bar: number,
	numerator: number,
	denominator: number,
};

export type TrackSpec = {
	id: string,
	kind?: string,
	name: string,
	clips: ClipSpec[],
	midiClips?: MidiClipSpec[],
	instrument?: InstrumentSpec | null,
	volumeDb: number | null,
	pan: number | null,
	muted: boolean,
	solo: boolean,
	effects: EffectSpec[],
	sends: SendSpec[],
	outputBusId?: string | null,
};

export type TransportSpec = {
	bpm: number | null,
	tempoPoints?: TempoPointSpec[],
	timeSignatures?: TimeSignaturePointSpec[],
	playheadSec: number | null,
	isPlaying: boolean,
	loop: LoopSpec,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

